qemu-system-x86_64 \
    -drive format=raw,file=myos.img,if=ide \
	-cpu qemu64,+cmov \
    -S -s \
    -chardev stdio,id=char0,mux=on -serial chardev:char0 -mon chardev=char0 \
    -nographic \
    -m 512M \
    -d int,cpu_reset \
    -D qemu.log \
    -cpu max \
    -smp 4