#include <hal/config_arch.h>
ENTRY(_start)
SECTIONS {
    . = KERNEL_FINAL_LDR_VADDR;
    .text_ap_start KERNEL_FINAL_LDR_VADDR : AT(KERNEL_FINAL_LDR_VADDR) {
        KEEP(*(.text_ap_start))
    }

    .text : {
        *(.text)
    }

    . = ALIGN(0x1000);
    .data : {
        *(.data)
    }
    . = ALIGN(4096);
    .bss : {
        *(.bss)
    }
    . = ALIGN(4096);
    .stack (NOLOAD): ALIGN(4096)
    {
        __stack_bottom = .;
        . += 0x2000;
        __stack_top = .;
    }
    . = ALIGN(4096);
    .mem_info (NOLOAD): ALIGN(4096) {
        __mem_info_bottom = .;
        . += 0x1000;
        __mem_info_top = .;
    }
    . = ALIGN(4096);
    .pgtable (NOLOAD): ALIGN(4096) {
        __pgtable_bottom = .;
        . += 0x300000;
        __pgtable_top = .;
    }

    . = ALIGN(4096);
    __percpu_seg_start = .;
    .percpu 0 : AT(__percpu_start) { //注意: 需要从0开始，因为为后续percpu就是段
        __percpu_start = .; 
        QUAD(0); //这部分存储percpu分配的内存地址
        *(.percpu); //所有.percpu段
        *(.percpu.shared_aligned); //需要特殊的多核共享的段
        __percpu_end = .;
    }
    
    __percpu_sz = __percpu_end - __percpu_start;
    . = __percpu_seg_start + __percpu_sz;
    .drv_init : {
        __drv_init_start = .;
        KEEP(*(.drv_init))
        KEEP(*(.drv_init.*))
        __drv_init_end = .;
    }
    . = ALIGN(4096);
    .smp_apic_data : {
        __smp_apic_data = .;
        . += 8 * 3;
        . += 8 * MAX_SUPPORTED_CORES;
        . += 8 * MAX_IO_APICS;
        . += 8 * MAX_IRQ_OVERRIDE_ENTRIES;
    }
    . = ALIGN(4096);
    __kernel_end = .;
}