#include <config_arch.h>
ENTRY(_start)
SECTIONS {
    . = KERNEL_FINAL_LDR_VADDR;
    . = ALIGN(4096);
    .bss : {
        *(.bss)
    }
    . = ALIGN(4096);
    .stack (NOLOAD): ALIGN(4096)
    {
        __stack_bottom = .;
        . += 0x2000;
        __stack_top = .;
    }
    . = ALIGN(4096);
    .pid_0_stack (NOLOAD): ALIGN(4096)
    {
        __pid_0_stack_bottom = .;
        . += 0x2000;
    }
    . = ALIGN(4096);
    .mem_info (NOLOAD): ALIGN(4096) {
        __mem_info_bottom = .;
        . += 0x1000;
        __mem_info_top = .;
    }
    . = ALIGN(4096);
    .pgtable (NOLOAD): ALIGN(4096) {
        __pgtable_bottom = .;
        . += 0x300000;
        __pgtable_top = .;
    }

    . = ALIGN(4096);
    __percpu_seg_start = .;
    .percpu 0 : AT(__percpu_start) { //注意: 需要从0开始，因为为后续percpu就是段
        __percpu_start = .; 
        QUAD(0); //这部分存储percpu分配的内存地址
        *(.percpu); //所有.percpu段
        *(.percpu.shared_aligned); //需要特殊的多核共享的段
        __percpu_end = .;
    }
    
    __percpu_sz = __percpu_end - __percpu_start;
    . = __percpu_seg_start + __percpu_sz;
    . = ALIGN(4096);
    .bsp_percpu (NOLOAD): ALIGN(4096) {
        __bsp_percpu_start = .;
        . += __percpu_sz;
    }
    . = ALIGN(4096);

    .bsp_ist0 (NOLOAD): ALIGN(4096) {
        __bsp_ist0 = .;
        . += 8192;
    }
    .bsp_ist1 (NOLOAD): ALIGN(4096) {
        __bsp_ist1 = .;
        . += 8192;
    }
    .bsp_ist2 (NOLOAD): ALIGN(4096) {
        __bsp_ist2 = .;
        . += 8192;
    }
    .bsp_ist3 (NOLOAD): ALIGN(4096) {
        __bsp_ist3 = .;
        . += 8192;
    }
    .bsp_ist4 (NOLOAD): ALIGN(4096) {
        __bsp_ist4 = .;
        . += 8192;
    }
    .text : {
        *(.text)
    }
    . = ALIGN(0x1000);
    .data : {
        *(.data)
    }
    . = ALIGN(4096);

    .drv_init : {
        __drv_init_start = .;
        KEEP(*(.drv_init))
        KEEP(*(.drv_init.*))
        __drv_init_end = .;
    }
    . = ALIGN(4096);
    __kernel_end = .;
}