import csv
import sys
import os

syscalls = 512
rootdir = os.getcwd()
head_name = "syscall_id"
head_macro = "_TOYOS_{arch}_{head_name}"
arch = ""
systables = [0] * syscalls

def head_inc(f):
    head = """/* Generated by tools. DO NOT EDIT IT MANUALLY! */
#include <kernel/syscall/syscall.h>
"""

    f.write(head)
def end_inc(f):
    f.write("};")

def head_header(f):
    head = """/* Generated by tools. DO NOT EDIT IT MANUALLY! */

#ifndef {head_macro}
#define {head_macro}

""".format(head_macro = head_macro)
    f.write(head)

def end_header(f):
    f.write("#endif")

def write_header_line(cid, cname, f):
    linestr = "#define _sys_{cname} {cid}\n".format(cname = cname.strip(" "), cid = cid)
    f.write(linestr)

def open_syscall_table(arch):
    global systables
    table_path = "{rootdir}/arch/{arch}/systable.csv".format(rootdir=rootdir, arch = arch)
    with open(table_path, 'r' ,encoding = "utf-8") as f:
        r = csv.reader(f)
        next(r)
        for row in r:   
            cid = int(row[0])
            cname = str(row[1])
            cfuncname = str(row[2])
            systables[cid] = {
                "cname": cname,
                "cfuncname": "syscall_"+cfuncname.strip(" ")
            }

def gen_systable_ifd(arch):
    ifd_path = "{rootdir}/arch/{arch}/generated/{headname}.inc".format(rootdir=rootdir, arch = arch, headname = head_name)
    ihf = os.fdopen(os.open(ifd_path, os.O_CREAT | os.O_WRONLY | os.O_TRUNC | os.O_APPEND, 0o644), 'w') 
    head_inc(ihf)
    for i in systables:
        if(i!=0):
            ihf.write(f"extern long {i["cfuncname"]}();\n")
    
    ihf.write("\nconst syscall_fn syscall_table[{nr}] = {{\n".format(nr=syscalls))
    for i in range(syscalls):
        if systables[i] == 0:
            txt = "    (void*)empty_syscall,\n"
        else:
            txt = f"    (void*){systables[i]["cfuncname"]},\n"
        ihf.write(txt)
    end_inc(ihf)
    ihf.close()

def gen_systable_header(arch):
    head_path = "{rootdir}/arch/{arch}/generated/{headname}.h".format(rootdir=rootdir, arch = arch, headname = head_name)
    hf = os.fdopen(os.open(head_path, os.O_CREAT | os.O_WRONLY | os.O_TRUNC | os.O_APPEND , 0o644), 'w') 

    head_header(hf)
    for i in range(len(systables)):
        if systables[i] != 0:
            write_header_line(
                i,
                systables[i]["cname"],
                hf)
    end_header(hf)
    hf.close()

def help():
    print("usage: gen_systable.py <arch>")
    
def sys_param_check():
    global head_macro
    global arch
    args = sys.argv
    if len(args) != 2:
        help()
        return 0
    arch = args[1]
    head_macro = head_macro.format(arch = arch.upper(), head_name = head_name.upper())
    return 1

def main():
    if sys_param_check() == 0:
        return 0
    open_syscall_table(arch)
    gen_systable_header(arch)
    gen_systable_ifd(arch)
    
if __name__ == "__main__":
    main()