#include <kernel/cpu/smp.h>
#include <stdio.h>
#include <stddef.h>

#define OUTPUT_MEMBER_OFFSET(obj,name, member) printf("#define offset_" #name "_" #member" %ld\n", offsetof(obj, member))
#define OUTPUT_SIZE(obj,name) printf("#define size_" #name " %ld\n", sizeof(obj))

int main() {
    printf("/* Generated by tools. DO NOT EDIT IT MANUALLY! */\n");
    printf("#ifndef _TOYOS_GENERATED_OFFSET\n");
    printf("#define _TOYOS_GENERATED_OFFSET\n\n");
    OUTPUT_MEMBER_OFFSET(struct ap_resource_pack, ap_resource, rsp);
    OUTPUT_SIZE(struct ap_resource_pack, ap_resource);
    printf("\n#endif");
    return 0;
}