import os
import sys
from pathlib import Path

class HeaderGenerator:
    def __init__(self, name, filename, arch = None):
        self.name = name
        self.arch = arch
        self.rootdir = os.getcwd()

        if arch == None:
            self.path = f"{self.rootdir}/include/generated"
            self.headname = f"_TOYOS_GENERATED_{name.upper()}"
        else:
            self.path = f"{self.rootdir}/arch/{arch}/include/generated"
            self.headname = f"_TOYOS_{arch.upper()}_GENERATED_{name.upper()}"
        os.makedirs(self.path, exist_ok=True)
        self.fobject = os.fdopen(os.open(f"{self.path}/{filename}", os.O_CREAT | os.O_WRONLY | os.O_TRUNC | os.O_APPEND, 0o644), 'w') 

    def write(self, content):
        self.fobject.write(content)

    def close(self):
        self.fobject.close()

    def write_define(self, name, content):
        self.fobject.write(f"#define {name} {content}\n")

    def _ifd_header(self):
        head = f"""/* Generated by tools. DO NOT EDIT IT MANUALLY! */

#ifndef {self.headname}
#define {self.headname}

"""
        
        self.fobject.write(head)
    
    def generate(self):
        pass

    def _ifd_end(self):
        self.fobject.write("\n#endif")
        self.fobject.close()

def sys_param_check():
    args = sys.argv
    if len(args) != 2:
        return None
    arch = args[1]
    return arch