#ifndef _TOYOS_CONFIG
#define _TOYOS_CONFIG

#include <hal/config_arch.h>
#define CONFIG_GROUP_MAX_CNT 327680
#define PROCESS_STACK_PAGE 2

#define PAGE_PTE_ENTRIES 512
#define PG_BIG_PAGE_OFFSET 21
#define PG_BIG_PAGE_SZ (1<<PG_BIG_PAGE_OFFSET)
#define PG_BIG_PAGE_MASK ~(PG_BIG_PAGE_SZ-1)
#define PAGE_OFFSET 12
#define PAGE_SZ (1<<PAGE_OFFSET)
#define PAGE_MASK ~(PAGE_SZ-1)
#define SYSCALL_COUNT 512

#define CONFIG_EEVDF 1
#define CONFIG_IRQ_MS 4
#define CONFIG_PERCPU_SZ 0x100000
#endif